version: '3'
services:
    linuxconsole64-2024-fast:
        image: yledoare/ydfs-2.10
        volumes:
            - $HOME/iso:/home/linuxconsole2025/iso
        environment:
            BUILDYDFS: "fast"
            SLEEPTIME: 1
        security_opt:
            - seccomp:unconfined
